-- Tabela de Movimentos de Caixa
CREATE TABLE IF NOT EXISTS `cliente_petiscaria_cash_movements` (
  `id` CHAR(36) NOT NULL,
  `companyId` CHAR(36) NOT NULL,
  `locationId` CHAR(36) NULL,
  `cashRegisterId` CHAR(36) NOT NULL,
  `userId` CHAR(36) NOT NULL,
  `movementType` ENUM('opening', 'closing', 'sale', 'refund', 'withdrawal', 'deposit', 'expense', 'adjustment') NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `previousBalance` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `newBalance` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `paymentMethod` ENUM('cash', 'pix', 'credit_card', 'debit_card', 'bank_transfer', 'digital_wallet', 'voucher') NULL,
  `orderId` CHAR(36) NULL,
  `paymentId` CHAR(36) NULL,
  `reference` VARCHAR(255) NULL,
  `description` VARCHAR(500) NULL,
  `notes` VARCHAR(500) NULL,
  `metadata` JSON NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_company_cash_register` (`companyId`, `cashRegisterId`),
  INDEX `idx_location_cash_register` (`locationId`, `cashRegisterId`),
  INDEX `idx_company_movement_type` (`companyId`, `movementType`),
  INDEX `idx_location_movement_type` (`locationId`, `movementType`),
  INDEX `idx_company_created` (`companyId`, `createdAt`),
  INDEX `idx_location_created` (`locationId`, `createdAt`),
  INDEX `idx_company_user` (`companyId`, `userId`),
  INDEX `idx_location_user` (`locationId`, `userId`),
  CONSTRAINT `fk_cash_movements_company` FOREIGN KEY (`companyId`) REFERENCES `cliente_petiscaria_companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cash_movements_location` FOREIGN KEY (`locationId`) REFERENCES `cliente_petiscaria_locations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cash_movements_user` FOREIGN KEY (`userId`) REFERENCES `cliente_petiscaria_users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cash_movements_order` FOREIGN KEY (`orderId`) REFERENCES `cliente_petiscaria_orders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cash_movements_payment` FOREIGN KEY (`paymentId`) REFERENCES `cliente_petiscaria_payments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
