CREATE TABLE `cliente_petiscaria_customers` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `cpf` varchar(14) DEFAULT NULL,
  `cnpj` varchar(18) DEFAULT NULL,
  `type` varchar(50) NOT NULL DEFAULT 'individual',
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zipCode` varchar(10) DEFAULT NULL,
  `birthDate` date DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `totalSpent` decimal(10,2) NOT NULL DEFAULT '0.00',
  `totalOrders` int NOT NULL DEFAULT '0',
  `totalVisits` int NOT NULL DEFAULT '0',
  `lastVisitAt` timestamp NULL DEFAULT NULL,
  `lastOrderAt` timestamp NULL DEFAULT NULL,
  `averageTicket` decimal(10,2) NOT NULL DEFAULT '0.00',
  `preferences` json DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `companyId` varchar(36) NOT NULL,
  `locationId` varchar(36) DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_email_company` (`email`, `companyId`),
  UNIQUE KEY `uk_cpf_company` (`cpf`, `companyId`),
  UNIQUE KEY `uk_cnpj_company` (`cnpj`, `companyId`),
  KEY `idx_company_id` (`companyId`),
  KEY `idx_location_id` (`locationId`),
  KEY `idx_phone_company` (`phone`, `companyId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
