CREATE TABLE `cliente_petiscaria_order_items` (
  `id` varchar(36) NOT NULL,
  `productName` varchar(255) NOT NULL,
  `productDescription` text DEFAULT NULL,
  `unitPrice` decimal(10,2) NOT NULL,
  `quantity` int NOT NULL DEFAULT '1',
  `discount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `tax` decimal(10,2) NOT NULL DEFAULT '0.00',
  `totalPrice` decimal(10,2) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `specialInstructions` varchar(50) DEFAULT NULL,
  `isReady` boolean NOT NULL DEFAULT false,
  `readyTime` timestamp NULL DEFAULT NULL,
  `deliveredTime` timestamp NULL DEFAULT NULL,
  `preparationTime` int NOT NULL DEFAULT '0',
  `modifications` json DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `orderId` varchar(36) NOT NULL,
  `productId` varchar(36) DEFAULT NULL,
  `companyId` varchar(36) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`orderId`),
  KEY `idx_product_id` (`productId`),
  KEY `idx_company_id` (`companyId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
