-- Tabela de Pagamentos
DROP TABLE IF EXISTS `cliente_gp_payments`;
CREATE TABLE IF NOT EXISTS `cliente_gp_payments` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `companyId` CHAR(36) NOT NULL,
  `locationId` CHAR(36) NULL,
  `orderId` CHAR(36) NOT NULL,
  `customerId` CHAR(36) NULL,
  `status` ENUM('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded', 'partially_refunded') NOT NULL DEFAULT 'pending',
  `paymentMethod` ENUM('pix', 'credit_card', 'debit_card', 'cash', 'bank_transfer', 'digital_wallet', 'voucher') NOT NULL,
  `paymentType` ENUM('full', 'partial', 'installment', 'advance') NOT NULL DEFAULT 'full',
  `amount` DECIMAL(10,2) NOT NULL,
  `fee` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `discount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `tax` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `netAmount` DECIMAL(10,2) NOT NULL,
  `transactionId` VARCHAR(255) NULL,
  `authorizationCode` VARCHAR(255) NULL,
  `pixKey` VARCHAR(255) NULL,
  `pixQrCode` VARCHAR(255) NULL,
  `pixExpirationDate` VARCHAR(255) NULL,
  `cardBrand` VARCHAR(255) NULL,
  `cardLastDigits` VARCHAR(255) NULL,
  `installmentPlan` VARCHAR(255) NULL,
  `installments` INT NOT NULL DEFAULT 1,
  `notes` VARCHAR(500) NULL,
  `metadata` JSON NULL,
  `processedAt` TIMESTAMP NULL,
  `expiredAt` TIMESTAMP NULL,
  `refundedAt` TIMESTAMP NULL,
  `refundedAmount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `refundReason` VARCHAR(500) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_company_order` (`companyId`, `orderId`),
  INDEX `idx_location_order` (`locationId`, `orderId`),
  INDEX `idx_company_customer` (`companyId`, `customerId`),
  INDEX `idx_location_customer` (`locationId`, `customerId`),
  INDEX `idx_company_status` (`companyId`, `status`),
  INDEX `idx_location_status` (`locationId`, `status`),
  INDEX `idx_company_method` (`companyId`, `paymentMethod`),
  INDEX `idx_location_method` (`locationId`, `paymentMethod`),
  INDEX `idx_company_created` (`companyId`, `createdAt`),
  INDEX `idx_location_created` (`locationId`, `createdAt`),
  INDEX `idx_payments_tenant` (`tenantId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
