-- Criação da tabela de produtos (products)
CREATE TABLE IF NOT EXISTS `cliente_petiscaria_products` (
  `id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `promotionalPrice` decimal(10,2) DEFAULT NULL,
  `promotionalPriceValidUntil` date DEFAULT NULL,
  `type` varchar(50) DEFAULT 'food',
  `status` varchar(50) DEFAULT 'active',
  `image` varchar(255) DEFAULT NULL,
  `images` json DEFAULT NULL,
  `sku` varchar(50) DEFAULT NULL,
  `barcode` varchar(50) DEFAULT NULL,
  `weight` decimal(8,3) DEFAULT 0.000,
  `unit` varchar(20) DEFAULT NULL,
  `stockQuantity` int DEFAULT 0,
  `minStockLevel` int DEFAULT 0,
  `maxStockLevel` int DEFAULT 0,
  `preparationTime` int DEFAULT 0,
  `isAvailableForDelivery` boolean DEFAULT false,
  `isAvailableForTakeaway` boolean DEFAULT false,
  `isAvailableForDineIn` boolean DEFAULT false,
  `isVegetarian` boolean DEFAULT false,
  `isVegan` boolean DEFAULT false,
  `isGlutenFree` boolean DEFAULT false,
  `isSpicy` boolean DEFAULT false,
  `spicinessLevel` int DEFAULT 0,
  `allergens` json DEFAULT NULL,
  `nutritionalInfo` json DEFAULT NULL,
  `ingredients` json DEFAULT NULL,
  `cookingInstructions` json DEFAULT NULL,
  `servingSuggestions` json DEFAULT NULL,
  `sortOrder` int DEFAULT 0,
  `isFeatured` boolean DEFAULT false,
  `viewCount` int DEFAULT 0,
  `rating` decimal(3,2) DEFAULT 0.00,
  `ratingCount` int DEFAULT 0,
  `metadata` json DEFAULT NULL,
  `companyId` char(36) NOT NULL,
  `locationId` char(36) DEFAULT NULL,
  `categoryId` char(36) DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_name_locationId` (`name`, `locationId`),
  KEY `IDX_categoryId` (`categoryId`),
  KEY `IDX_companyId` (`companyId`),
  KEY `IDX_locationId` (`locationId`),
  KEY `IDX_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
