CREATE TABLE `cliente_petiscaria_stock_movements` (
  `id` varchar(36) NOT NULL,
  `type` varchar(50) NOT NULL,
  `reason` varchar(50) NOT NULL,
  `quantity` decimal(10,3) NOT NULL,
  `unitCost` decimal(10,2) NOT NULL DEFAULT '0.00',
  `totalCost` decimal(10,2) NOT NULL DEFAULT '0.00',
  `quantityBefore` decimal(10,3) NOT NULL DEFAULT '0.000',
  `quantityAfter` decimal(10,3) NOT NULL DEFAULT '0.000',
  `date` date NOT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `supplier` varchar(255) DEFAULT NULL,
  `batchNumber` varchar(255) DEFAULT NULL,
  `expiryDate` date DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `companyId` varchar(36) NOT NULL,
  `locationId` varchar(36) DEFAULT NULL,
  `productId` varchar(36) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_company_id` (`companyId`),
  KEY `idx_location_id` (`locationId`),
  KEY `idx_product_id` (`productId`),
  KEY `idx_type` (`type`),
  KEY `idx_reason` (`reason`),
  KEY `idx_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
