CREATE TABLE `cliente_petiscaria_tables` (
  `id` varchar(36) NOT NULL,
  `number` varchar(10) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'available',
  `shape` varchar(50) NOT NULL DEFAULT 'round',
  `capacity` int NOT NULL DEFAULT '2',
  `minCapacity` int NOT NULL DEFAULT '0',
  `maxCapacity` int NOT NULL DEFAULT '0',
  `xPosition` decimal(5,2) NOT NULL DEFAULT '0.00',
  `yPosition` decimal(5,2) NOT NULL DEFAULT '0.00',
  `sortOrder` int NOT NULL DEFAULT '0',
  `isActive` boolean NOT NULL DEFAULT true,
  `isReservable` boolean NOT NULL DEFAULT false,
  `isSmoking` boolean NOT NULL DEFAULT false,
  `isOutdoor` boolean NOT NULL DEFAULT false,
  `color` varchar(7) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `features` json DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `companyId` varchar(36) NOT NULL,
  `locationId` varchar(36) DEFAULT NULL,
  `areaId` varchar(36) DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_number_location` (`number`, `locationId`),
  KEY `idx_company_id` (`companyId`),
  KEY `idx_location_id` (`locationId`),
  KEY `idx_area_id` (`areaId`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
