DROP TABLE IF EXISTS `cliente_gp_users`;
CREATE TABLE IF NOT EXISTS `cliente_gp_users` (
  `id` char(36) NOT NULL,
  `tenantId` char(36) NOT NULL,
  `companyId` char(36) NOT NULL,
  `roleId` char(36) DEFAULT NULL,
  `locationId` char(36) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(50) DEFAULT 'waiter',
  `status` varchar(50) DEFAULT 'active',
  `avatar` varchar(255) DEFAULT NULL,
  `cpf` varchar(255) DEFAULT NULL,
  `birthDate` date DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zipCode` varchar(10) DEFAULT NULL,
  `salary` decimal(10,2) DEFAULT 0.00,
  `hireDate` date DEFAULT NULL,
  `isTwoFactorEnabled` boolean DEFAULT false,
  `twoFactorSecret` varchar(255) DEFAULT NULL,
  `lastLoginAt` timestamp NULL DEFAULT NULL,
  `lastLoginIp` varchar(45) DEFAULT NULL,
  `permissions` json DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_users_email_tenant` (`email`,`tenantId`),
  KEY `IDX_users_company` (`companyId`),
  KEY `IDX_users_location` (`locationId`),
  KEY `IDX_users_role` (`roleId`),
  KEY `IDX_users_tenant` (`tenantId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
