CREATE TABLE IF NOT EXISTS `cliente_gp_ingredients` (
  `id` CHAR(36) NOT NULL,
  `companyId` CHAR(36) NOT NULL,
  `locationId` CHAR(36) NULL,
  `categoryId` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `sku` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `ingredientType` ENUM('raw_material', 'processed', 'spice', 'condiment', 'liquid', 'dry', 'frozen', 'fresh') NOT NULL DEFAULT 'raw_material',
  `unit` ENUM('gram', 'kilogram', 'liter', 'milliliter', 'unit', 'package', 'bottle', 'can') NOT NULL DEFAULT 'gram',
  `currentStock` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `minStock` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `maxStock` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `unitCost` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `unitPrice` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `supplierName` VARCHAR(255) NULL,
  `brand` VARCHAR(255) NULL,
  `barcode` VARCHAR(100) NULL,
  `allergens` VARCHAR(500) NULL,
  `nutritionalInfo` JSON NULL,
  `storageConditions` JSON NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_company_category` (`companyId`, `categoryId`),
  INDEX `idx_location_category` (`locationId`, `categoryId`),
  INDEX `idx_company_type` (`companyId`, `ingredientType`),
  INDEX `idx_location_type` (`locationId`, `ingredientType`),
  INDEX `idx_company_name` (`companyId`, `name`),
  INDEX `idx_location_name` (`locationId`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
